### ISSUE TITLE
Application: Share Flags

### ISSUE THREAD

**Issue by DylanAkp** [jacopotediosi/GAppsMod#87]
## Summary
[NOTE]: # ( Provide a brief overview of what the new feature is all about )
People ask for flags X or Y to be implemented, some other users will enable flags and watch the changes to find the one they want.

## Solution
[NOTE]: # ( A clear and concise description of what you want to happen )
Creating a "community flag" tab or option, so that everyone can share their flags with explanation on what it does, and everyone can use them

## Examples
[NOTE]: # ( Show us a picture or mock-up of your proposal )
Same as Recommanded flags, but for community flags

## Alternatives
[NOTE]: # ( A clear and concise description of any alternative solutions or features you've considered )
A repository or something like this to share flags (less convenient)

## Context
[NOTE]: # ( Why does this feature matter to you? What unique circumstances do you have? )
This feature allows user to share their flags and to be implemented faster

**Comment by jacopotediosi** [comment]
Thanks so much for your suggestion.

Implementing a feature like this would require significant effort to integrate a connection to a "community mods" repository within the application. Any mods in that repository would still need to undergo review by either myself or other trusted contributors, as applying mods can potentially impact device stability and security.

Furthermore, actually the mods applied by GAppsMod are not limited to just setting boolean flags to true/false.

Currently, the mods in our project can manipulate the filesystem (e.g., by editing files within `/data/data folders`) or modify the five types of flags contained in the phenotype database (`intVal`, `boolVal`, `floatVal`, `stringVal`, and `extensionVal`).

In particular, `extensionVal` flags contain raw bytes, often in the form of protobuf structures, which requires intricate reverse engineering work on the target Google applications for which mods are being developed. If you're interested in this aspect, you can refer to the following example where we perform such work: https://github.com/jacopotediosi/GAppsMod/blob/6970162e374a96b677fb6b1f2caf058534cf8287/app/src/main/java/com/jacopomii/gappsmod/ui/fragment/SuggestedModsFragment.java#L492-L532

Filesystem mods are also quite complex. For example, to add contacts to the list for which the Phone by Google application automatically record calls (#26), it is necessary to reverse engineer the protobuf structure contained in the `/data/data/com.google.android.dialer/files/CallRecordingSettingsData.pb` file.

Since these types of mods don't have a standard, the code has to be written manually. Therefore, users would still not be able to submit these mods directly through the application itself, but would have to open an issue or pull request on GitHub to contribute their own mods.

For the reasons mentioned above, it is not worth implementing a community mods repository, because it would be limited to boolean mods only.
Instead, I encourage you to submit mods through issues or pull requests so that I can add them to the "Suggested Mods" section.

Additionally, I already have plans to create a documentation (wiki) in the future where everyone can contribute by explaining the functionality of each flag in the phenotype database.
