### ISSUE TITLE
Support for Shizuku

### ISSUE THREAD

**Issue by PranavPurwar** [jacopotediosi/GAppsMod#88]
Hey, I just wanted to ask if it would be possible to achieve the same functionality using Shizuku. It would become really useful for those not having their devices rooted. Thanks!

**Comment by jacopotediosi** [comment]
Hi and thanks for your suggestion.

GAppsMod works modifying files within the `/data/data` directory. Even if I were to add Shizuku support, it would still require Shizuku to have root privileges to access and modify these files, because ADB privileges aren't sufficient (https://github.com/RikkaApps/Shizuku-API#differents-of-the-privilege-betweent-adb-and-root).

Given this requirement, I wanted to ask you if it would still make sense to implement such a feature.
Please let me know your thoughts on this matter, and if you have any further questions or suggestions. I'm open to discussing alternative solutions or considering other options that could enhance the usability of my app.

**Comment by PranavPurwar** [comment]
Hmm, I dont think it'd still be feasible to use Shizuku when you already have root. Nevertheless, thanks for clearing my query!
